# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-08 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20190707_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidebar',
            old_name='display',
            new_name='display_type',
        ),
    ]
