# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190703_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(verbose_name='网站'),
        ),
    ]
